# Generated by Django 5.2.17 on 2026-08-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Short line shown under the title on the Resources page, e.g. a call to action.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='resource_covers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this resource from the public Resources page without deleting it.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
