# Generated by Django 5.2.16 on 2026-07-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='What learners will understand or be able to do after completing this course.'),
        ),
    ]
