# Generated by Django 5.2.16 on 2026-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_learning_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, help_text='Optional alphanumeric course code displayed on the course page.', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='A longer descriptive overview of the course shown before enrollment.'),
        ),
    ]
