# Generated by Django 5.2.16 on 2026-07-12 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_code_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('duration', models.CharField(blank=True, help_text='Example: 15 min', max_length=50)),
                ('module_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('mixed', 'Mixed')], default='article', max_length=20)),
                ('learning_mode', models.CharField(choices=[('self_paced', 'Self-paced'), ('live', 'Live'), ('blended', 'Blended')], default='self_paced', max_length=20)),
                ('overview', models.TextField(blank=True, help_text='A short summary of the module.')),
                ('content', models.TextField(blank=True, help_text='The full content for this module.')),
                ('module_summary', models.TextField(blank=True, help_text='A recap shown at the end of the module.')),
                ('knowledge_check', models.TextField(blank=True, help_text='Questions or prompts for reflection.')),
                ('practical_activity', models.TextField(blank=True, help_text='A practical exercise for the learner.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
