# Generated by Django 5.2.16 on 2026-08-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursemodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, help_text='The main learning material for the course. Supports plain text/markdown-style paragraphs.'),
        ),
    ]
