# Generated by Django 5.2.17 on 2026-09-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('learner_guide', 'Learner guide'), ('slides', 'Slide deck'), ('video', 'Video'), ('transcript', 'Transcript'), ('worksheet', 'Worksheet'), ('reference', 'Reference')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='course_assets/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=40)),
                ('language', models.CharField(default='en', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='courses.course')),
                ('module', models.ForeignKey(blank=True, help_text='Leave blank when the resource applies to the whole course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='courses.coursemodule')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
