# Generated by Django 5.2.17 on 2026-09-29 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseasset',
            options={'ordering': ['order', 'id'], 'permissions': [('review_courseasset', 'Can approve course assets for publication'), ('publish_courseasset', 'Can publish and retire course assets'), ('bulk_import_courseasset', 'Can bulk import course asset metadata')]},
        ),
        migrations.AddField(
            model_name='courseasset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_course_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_course_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
