# Generated by Django 5.2.17 on 2026-10-02 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courseasset_options_courseasset_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseasset',
            name='content_type',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='The earlier asset superseded by this separately reviewed replacement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_assets', to='courses.courseasset'),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_course_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Supabase Storage object path, when this resource is stored in Supabase.', max_length=500),
        ),
        migrations.CreateModel(
            name='ContentUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('learner_guide', 'Learner guide'), ('slides', 'Slide deck'), ('video', 'Video'), ('transcript', 'Transcript'), ('worksheet', 'Worksheet'), ('reference', 'Reference')], max_length=20)),
                ('content_type', models.CharField(max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_intents', to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_intents', to='courses.coursemodule')),
                ('replacement_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_upload_intents', to='courses.courseasset')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_upload_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
