# Generated by Django 5.2.17 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_courseasset_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="paralearn_assessment_id",
            field=models.CharField(
                blank=True,
                help_text="The ParaLearn CBT assessment identifier. A course cannot launch an authoritative assessment until this is configured.",
                max_length=200,
            ),
        ),
    ]
