# Generated by Django 5.2.17 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_course_paralearn_assessment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseasset",
            name="external_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
