# Generated by Django 5.2.17 on 2026-10-02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_course_paralearn_assessment_id"),
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAssessmentAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("paralearn", "ParaLearn CBT")], default="paralearn", max_length=30)),
                ("launch_idempotency_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("provider_attempt_id", models.CharField(blank=True, max_length=200, null=True)),
                ("provider_result_id", models.CharField(blank=True, max_length=200, null=True)),
                ("status", models.CharField(choices=[("created", "Created"), ("launched", "Launched"), ("result_pending", "Result pending"), ("passed", "Passed"), ("failed", "Failed"), ("launch_failed", "Launch failed"), ("reconciliation_failed", "Reconciliation failed")], default="created", max_length=30)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                ("launch_count", models.PositiveIntegerField(default=0)),
                ("reconciliation_count", models.PositiveIntegerField(default=0)),
                ("launched_at", models.DateTimeField(blank=True, null=True)),
                ("result_received_at", models.DateTimeField(blank=True, null=True)),
                ("result_verified_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("last_launch_error", models.TextField(blank=True)),
                ("last_reconciliation_error", models.TextField(blank=True)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessment_attempts", to="courses.course")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="course_assessment_attempts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ParaLearnWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=200, unique=True)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("signature_verified_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                ("attempt", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="paralearn_events", to="learning.courseassessmentattempt")),
            ],
            options={"ordering": ["-received_at"]},
        ),
        migrations.AddConstraint(
            model_name="courseassessmentattempt",
            constraint=models.UniqueConstraint(condition=Q(("provider_attempt_id__isnull", False)), fields=("provider", "provider_attempt_id"), name="unique_provider_assessment_attempt"),
        ),
        migrations.AddConstraint(
            model_name="courseassessmentattempt",
            constraint=models.UniqueConstraint(condition=Q(("provider_result_id__isnull", False)), fields=("provider", "provider_result_id"), name="unique_provider_assessment_result"),
        ),
        migrations.AddConstraint(
            model_name="courseassessmentattempt",
            constraint=models.CheckConstraint(condition=Q(("score__isnull", True), Q(("score__gte", 0), ("score__lte", 100)), _connector="OR"), name="assessment_attempt_score_in_range"),
        ),
    ]
