# Generated by Django 5.2.17 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_curriculum_and_module_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseassessmentattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("launched", "Launched"),
                    ("result_pending", "Result pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("disqualified", "Disqualified — examiner review required"),
                    ("launch_failed", "Launch failed"),
                    ("reconciliation_failed", "Reconciliation failed"),
                ],
                default="created",
                max_length=30,
            ),
        ),
    ]
